FROM jenkins/jenkins:2.440.3-lts-jdk17
USER root

# Copiar requirements antes de tudo
COPY ./requirements.txt /tmp/requirements.txt

# Instalar dependências do sistema
RUN apt update && \
    apt install -y python3 python3-pip python3-venv build-essential g++ git && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip setuptools wheel

# Instalar dependências Python
RUN /opt/venv/bin/pip install --no-cache-dir --prefer-binary -r /tmp/requirements.txt

# Copiar plugins Jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Groovy de configuração
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy

# Configurações de ambiente
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400"
ENV JENKINS_URL="http://jenkins:10000"
ENV FLUENTD_HOST="fluentd"
ENV FLUENTD_PORT="24224"
ENV ACCESS_KEY=${ACCESS_KEY}
ENV SECRET_KEY=${SECRET_KEY}
ENV PATH="/opt/venv/bin:$PATH"

USER jenkins