FROM python:3.9-slim-buster

# Define diretório de trabalho
WORKDIR /usr/src/app

# Instala dependências do sistema para PostgreSQL e builds de pacotes Python
#RUN apt-get update && \
#    apt-get install -y gcc libpq-dev curl && \
#    rm -rf /var/lib/apt/lists/*

RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list && \
    sed -i '/security.debian.org/d' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y gcc libpq-dev curl && \
    rm -rf /var/lib/apt/lists/*
    
# Instala pacotes Python com versões especificadas
RUN pip install --upgrade pip && \
    pip install \
        awscli==1.24.7 \
        boto3==1.23.7 \
        mlflow==1.30.0 \
        protobuf==3.20.1 \
        psycopg2-binary==2.9.9

# Expõe porta do MLflow server
EXPOSE 5000

# Comando padrão para iniciar o MLflow Server (parâmetros passados via docker-compose)
CMD ["mlflow", "server"]