FROM python:3.10-slim

RUN apt-get update && apt-get install -y gcc curl git

ENV DAGSTER_HOME=/opt/dagster/dagster_home
ENV PYTHONPATH=/opt/dagster/app
WORKDIR /opt/dagster/app

COPY requirements.txt .

# Aumenta o timeout de leitura para 100 segundos
RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt

COPY . .

CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]