version: '3.7'

services:
  redis:
    image: redis:7
    container_name: spinnaker-redis
    ports:
      - "6379:6379"

  minio-spin:
    image: minio/minio
    container_name: spinnaker-minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: spinnaker
      MINIO_SECRET_KEY: spinnaker123
    volumes:
      - spin-minio-data:/data
    command: server /data

  halyard:
    image: gcr.io/spinnaker-marketplace/halyard:stable
    container_name: halyard
    environment:
      - USER=root
    volumes:
      - halyard-config:/opt/spinnaker/config
      - ~/.hal:/home/spinnaker/.hal
      - ~/.spinnaker:/home/spinnaker/.spinnaker
    ports:
      - "8064:8064"
    command:
      - bash
      - -c
      - |
        hal config storage s3 edit --endpoint http://minio-spin:9000 --access-key-id spinnaker --secret-access-key spinnaker123 --bucket spin-bucket &&
        hal config storage edit --type s3 &&
        hal config version edit --version 1.30.1 &&
        hal deploy apply && 
        hal deploy connect

  deck:
    image: gcr.io/spinnaker-marketplace/deck:2.31.0
    container_name: deck
    ports:
      - "9002:9000"
    environment:
      API_HOST: http://gate:8084

  gate:
    image: gcr.io/spinnaker-marketplace/gate:1.33.0
    container_name: gate
    ports:
      - "8084:8084"

volumes:
  halyard-config:
  spin-minio-data: