# .github/workflows/ml_pipeline.yml
name: CD4ML Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest cd4ml/problems/rendimento/tests --maxfail=2 --disable-warnings

      - name: Executar pipeline (modo leve)
        run: |
          python run_python_script.py pipeline rendimento default default default default